name: ActionCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bloggerify
        uses: ./
        with:
          path: './demo'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bloggerify Demo
          path: "demo/Bloggerify/*"